// Code generated by halologgen from schema.yaml. DO NOT EDIT.

// Package applog is a compile-time-checked logging facade: every
// loggable field is a typed method, so a misspelled key or wrong-typed
// value fails the build instead of corrupting a log line. Keys are
// pre-declared once; their escaped JSON fragments are frozen by the
// generated fragments test.
package applog

import (
	"github.com/go-gen-ecosystem/halolog"
	"github.com/go-gen-ecosystem/halolog/core"
)

// Pre-declared keys — escaping computed at generation time, pinned by test.
var (
	keyUserID     = halolog.Key("user_id")
	keyTenant     = halolog.Key("tenant")
	keyStatus     = halolog.Key("status")
	keyDurationMS = halolog.Key("duration_ms")
	keyRatio      = halolog.Key("ratio")
	keyCacheHit   = halolog.Key("cache_hit")
	keyErrField   = halolog.Key("err")
	keyPayload    = halolog.Key("payload")
)

// Logger wraps a core logger with this schema's typed vocabulary.
type Logger struct{ l *core.Logger }

// Wrap adapts a configured core logger to the schema facade.
func Wrap(l *core.Logger) Logger { return Logger{l: l} }

// Unwrap exposes the underlying core logger (escape hatch).
func (w Logger) Unwrap() *core.Logger { return w.l }

// With opens a schema-typed context builder; bound fields are encoded once
// and cost one memcpy per line thereafter.
func (w Logger) With() Ctx { return Ctx{c: w.l.With()} }

// Ctx accumulates schema-typed bound fields for a child logger.
type Ctx struct{ c core.Context }

// UserID binds the "user_id" field.
func (c Ctx) UserID(v string) Ctx { return Ctx{c: c.c.Str(keyUserID, v)} }

// Tenant binds the "tenant" field.
func (c Ctx) Tenant(v string) Ctx { return Ctx{c: c.c.Str(keyTenant, v)} }

// Status binds the "status" field.
func (c Ctx) Status(v int) Ctx { return Ctx{c: c.c.Int(keyStatus, v)} }

// DurationMS binds the "duration_ms" field.
func (c Ctx) DurationMS(v int64) Ctx { return Ctx{c: c.c.Int64(keyDurationMS, v)} }

// Ratio binds the "ratio" field.
func (c Ctx) Ratio(v float64) Ctx { return Ctx{c: c.c.Float64(keyRatio, v)} }

// CacheHit binds the "cache_hit" field.
func (c Ctx) CacheHit(v bool) Ctx { return Ctx{c: c.c.Bool(keyCacheHit, v)} }

// ErrField binds the "err" field.
func (c Ctx) ErrField(v error) Ctx { return Ctx{c: c.c.Err(keyErrField, v)} }

// Payload binds the "payload" field.
func (c Ctx) Payload(v interface{}) Ctx { return Ctx{c: c.c.Any(keyPayload, v)} }

// Logger derives the child logger carrying the bound fields.
func (c Ctx) Logger() Logger { return Logger{l: c.c.Logger()} }

// Level-first lines: a disabled level costs a single check.

// Trace opens a TRACE-level line.
func (w Logger) Trace() Line { return Line{ln: w.l.TraceLine()} }

// Debug opens a DEBUG-level line.
func (w Logger) Debug() Line { return Line{ln: w.l.DebugLine()} }

// Info opens an INFO-level line.
func (w Logger) Info() Line { return Line{ln: w.l.InfoLine()} }

// Warn opens a WARN-level line.
func (w Logger) Warn() Line { return Line{ln: w.l.WarnLine()} }

// Error opens an ERROR-level line.
func (w Logger) Error() Line { return Line{ln: w.l.ErrorLine()} }

// Line is a schema-typed level-first line builder.
type Line struct{ ln core.Line }

// UserID adds the "user_id" field.
func (e Line) UserID(v string) Line { return Line{ln: e.ln.Str(keyUserID, v)} }

// Tenant adds the "tenant" field.
func (e Line) Tenant(v string) Line { return Line{ln: e.ln.Str(keyTenant, v)} }

// Status adds the "status" field.
func (e Line) Status(v int) Line { return Line{ln: e.ln.Int(keyStatus, v)} }

// DurationMS adds the "duration_ms" field.
func (e Line) DurationMS(v int64) Line { return Line{ln: e.ln.Int64(keyDurationMS, v)} }

// Ratio adds the "ratio" field.
func (e Line) Ratio(v float64) Line { return Line{ln: e.ln.Float64(keyRatio, v)} }

// CacheHit adds the "cache_hit" field.
func (e Line) CacheHit(v bool) Line { return Line{ln: e.ln.Bool(keyCacheHit, v)} }

// ErrField adds the "err" field.
func (e Line) ErrField(v error) Line { return Line{ln: e.ln.Err(keyErrField, v)} }

// Payload adds the "payload" field.
func (e Line) Payload(v interface{}) Line { return Line{ln: e.ln.Any(keyPayload, v)} }

// Msg completes the line with a message and writes it.
func (e Line) Msg(msg string) { e.ln.Msg(msg) }

// Send completes the line with an empty message.
func (e Line) Send() { e.ln.Send() }
