// Code generated by halologgen from schema.yaml. DO NOT EDIT.

package applog

import (
	"bytes"
	"testing"
)

// TestKeyFragmentsFrozen pins every key's escaped JSON fragment to the form
// computed at generation time. If the runtime escaper and the generator ever
// disagree, this fails the consumer's build — escaping is decided once, at
// generation, and reviewed like any other code.
func TestKeyFragmentsFrozen(t *testing.T) {
	pins := []struct {
		name     string
		fragment string
		got      []byte
	}{
		{"user_id", ",\"user_id\":", keyUserID.JSONFragment},
		{"tenant", ",\"tenant\":", keyTenant.JSONFragment},
		{"status", ",\"status\":", keyStatus.JSONFragment},
		{"duration_ms", ",\"duration_ms\":", keyDurationMS.JSONFragment},
		{"ratio", ",\"ratio\":", keyRatio.JSONFragment},
		{"cache_hit", ",\"cache_hit\":", keyCacheHit.JSONFragment},
		{"err", ",\"err\":", keyErrField.JSONFragment},
		{"payload", ",\"payload\":", keyPayload.JSONFragment},
	}
	for _, p := range pins {
		if !bytes.Equal(p.got, []byte(p.fragment)) {
			t.Fatalf("key %q: fragment drifted from generation-time form: got %q want %q",
				p.name, p.got, p.fragment)
		}
	}
}
