# @author Admilson B. F. Cossa
name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    uses: go-gen-ecosystem/.github/.github/workflows/reusable-go-ci.yml@main
    with:
      coverage-threshold: 60
